# Generated by Django 4.2.19 on 2025-02-18 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(default=datetime.date.today, help_text='Enter date', max_length=15, verbose_name='End_date'),
        ),
    ]
