# Generated by Django 4.2.19 on 2025-02-19 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_alter_schedule_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='status',
            new_name='membership_status',
        ),
    ]
