# Generated by Django 4.2.19 on 2025-02-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_trainer_professional_history_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ('last_name', 'first_name')},
        ),
        migrations.AddField(
            model_name='trainer',
            name='trainer_cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/trainer_covers', verbose_name='trainer_cover'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='ts_cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/ts_covers', verbose_name='training_session_cover'),
        ),
    ]
