# Generated by Django 4.2.19 on 2025-02-19 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym', '0005_alter_trainer_options_trainer_trainer_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='professional_history',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
