# Generated by Django 4.2.19 on 2025-02-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_alter_trainer_professional_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default-user.png', upload_to='profile_pics'),
        ),
    ]
