# Generated by Django 4.2.19 on 2025-02-20 08:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gym.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym', '0007_alter_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(default=gym.models.get_current_time, help_text='Enter End time', verbose_name='End time'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(default=gym.models.get_current_time, help_text='Enter start time', verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(default=gym.models.get_current_time, help_text='Enter end date', verbose_name='End_date'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=models.DateField(default=gym.models.get_current_time, help_text='Enter start date', verbose_name='Start_date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.date.today, help_text='Enter date', verbose_name='Payment_date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(default=datetime.date.today, help_text='Enter date', verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(default=datetime.date.today, help_text='Enter date', verbose_name='Start date'),
        ),
    ]
