# Generated by Django 4.2.19 on 2025-02-20 11:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_schedule_end_time_schedule_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.trainer'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.client'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(default=datetime.date.today, help_text='Enter end date', verbose_name='End_date'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=models.DateField(default=datetime.date.today, help_text='Enter start date', verbose_name='Start_date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.membership'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.client'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='training_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='gym.trainingsession'),
        ),
        migrations.AlterField(
            model_name='trainerschedule',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.schedule'),
        ),
        migrations.AlterField(
            model_name='trainerschedule',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.trainer'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.schedule'),
        ),
    ]
