# Generated by Django 4.2.19 on 2025-02-20 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_membership_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='client',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='client',
        ),
        migrations.AddField(
            model_name='membership',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter your phone number', max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.profile'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(blank=True, choices=[('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly'), ('T', 'Trial')], default='T', help_text='Membership type', max_length=1, verbose_name='type'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
