# Generated by Django 4.2.19 on 2025-02-20 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_trainingsession_trainer_alter_membership_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='trainer',
            field=models.ForeignKey(default='Missing Trainer', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='gym.trainer'),
            preserve_default=False,
        ),
    ]
