# Generated by Django 4.2.19 on 2025-02-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_remove_membership_client_remove_reservation_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/trainer_covers'),
        ),
    ]
