# Generated by Django 4.2.19 on 2025-02-20 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_alter_trainingsession_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='trainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='gym.trainer'),
        ),
    ]
