# Generated by Django 4.2.19 on 2025-02-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0011_trainer_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='trainer_cover',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='duration',
            field=models.DurationField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(blank=True, choices=[('B', 'Basic'), ('F', 'Flexible'), ('P', 'Premium'), ('T', 'Trial')], default='T', help_text='Membership type', max_length=1, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='ts_cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/ts_covers', verbose_name='training session cover'),
        ),
    ]
