# Generated by Django 4.2.19 on 2025-02-21 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_remove_trainer_trainer_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='trainer',
        ),
        migrations.AddField(
            model_name='trainerschedule',
            name='training_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.trainingsession'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='location',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='duration',
            field=models.DurationField(default='01:00:00'),
        ),
    ]
