# Generated by Django 4.2.19 on 2025-02-21 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0014_remove_schedule_end_date_remove_schedule_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='profile',
        ),
        migrations.AddField(
            model_name='payment',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.profile'),
        ),
    ]
