# Generated by Django 4.2.19 on 2025-02-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0015_remove_membership_profile_payment_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('p', 'Processing'), ('a', 'Active'), ('e', 'Expired')], default='p', help_text='Membership status', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.FloatField(help_text='Enter payment price', verbose_name='Price EUR'),
        ),
    ]
