# Generated by Django 4.2.19 on 2025-02-21 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0016_payment_payment_status_alter_payment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.profile'),
        ),
    ]
