# Generated by Django 4.2.19 on 2025-02-21 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0018_remove_membership_name_alter_membership_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='week_day',
        ),
        migrations.AddField(
            model_name='reservation',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.schedule'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.trainer'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='training_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.trainingsession'),
        ),
    ]
