# Generated by Django 4.2.19 on 2025-02-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0019_remove_schedule_week_day_reservation_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='training_session',
        ),
    ]
