# Generated by Django 4.2.19 on 2025-02-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0021_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('p', 'Processing'), ('a', 'Paid'), ('e', 'Expired')], default='p', help_text='Membership status', max_length=1, verbose_name='status'),
        ),
    ]
