# Generated by Django 4.2.19 on 2025-02-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0024_displaymembership_alter_payment_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaymembership',
            name='price',
            field=models.FloatField(default=None, help_text='Enter membership price', verbose_name='Price EUR'),
            preserve_default=False,
        ),
    ]
