# Generated by Django 4.2.19 on 2025-02-21 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0025_displaymembership_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaymembership',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
