# Generated by Django 4.2.19 on 2025-02-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0027_trainingsessionreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaymembership',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/membership_covers'),
        ),
    ]
