# Generated by Django 4.2.19 on 2025-02-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0028_displaymembership_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='description',
        ),
    ]
