# Generated by Django 4.2.19 on 2025-02-22 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0031_reservation_rez_holder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='profile',
        ),
    ]
