# Generated by Django 4.2.19 on 2025-02-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0036_remove_trainingsession_max_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Enter max capacity', null=True, verbose_name='Capacity'),
        ),
    ]
