# Generated by Django 4.2.19 on 2025-02-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0037_alter_schedule_max_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='rez_holder',
            new_name='user',
        ),
    ]
